$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: my_train
display_name: Train
type: command
inputs:
  scoring_result:
    type: uri_folder
outputs:
  eval_output:
    type: uri_folder
environment: azureml://registries/azureml/environments/sklearn-1.5/labels/latest
code: ./train_src
command: >-
  python train.py  --scoring_result ${{inputs.scoring_result}}  --eval_output ${{outputs.eval_output}}
tags:
  contact: ml-team@example.com
  owner: ml-team
  type: evaluation
  repo: https://github.com/kamimanzoor/azureml-components-mono/components/my_train